### PR TITLE
LPS-54874

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @JorgeFerrer 

Just checking if you're aware of this one as well?
Also related to Mail Portlet...

**Comment by JorgeFerrer** [comment]
I saw it but wasn't sure what to do about it. @sergiogonzalez @marcellustavares whose team is currently owning Web Form?

**Comment by sergiogonzalez** [comment]
I guess that it's @marcellustavares . Collab team doesn't own it.

**Comment by marcellustavares** [comment]
Yes, we're taking care of it for now. Thanks

**Comment by JorgeFerrer** [comment]
Thanks @marcellustavares, should Hugo send you the pull or can you pick it from here?

I'm going to close it here since you can grab it even if it's closed.

**Comment by zxdgoal** [comment]
@marcellustavares 

Did you get time for reviewing this pr?

Thanks
John.

**Comment by marcellustavares** [comment]
Not yet, will get this during the day.

Thanks

**Comment by marcellustavares** [comment]
Submitted to https://github.com/brianchandotcom/liferay-plugins/pull/4495

**Comment by hhuijser** [comment]
Thanks @JorgeFerrer @marcellustavares 

Will send straight to Marcellus next time...

**Pull request closed without merging**
